# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1483940727);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1483940847);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1483940967);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1458642951);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 245760);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20160924090433");
user_pref("browser.startup.homepage_override.mstone", "2.2.0");
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.5.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/palemoon/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1475183641000,\"rdfTime\":1475183641000}}}]");
user_pref("extensions.lastAppVersion", "26.5.0");
user_pref("extensions.lastPlatformVersion", "2.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("goanna.buildID", "20160924090433");
user_pref("goanna.mstone", "2.2.0");
user_pref("idle.lastDailyNotification", 1483942175);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 17272);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1483940605);
user_pref("xpinstall.whitelist.add", "");
